version: "3.7"

volumes:
  autobase-data:

services:
  postgres:
    container_name: autobase-db
    image: postgres:15.8-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: vst
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autobase-database
    volumes:
      - autobase-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

